### ISSUE TITLE
Proposal: Use Java 8's Nashorn JS Engine for Predicate Expectations

### ISSUE THREAD

**Issue by slu-it** [testIT-LivingDoc/livingdoc2#33]
I implemented a Prototype on this branch:
https://github.com/slu-it/livingdoc2/tree/predicates

**Comment by bitterblue** [comment]
My argument against Nashorn is, that it is unnecessarily complex. Sure, it's cheap to implement, but the expectation DSL is something non-technical domain experts will have to use. Their user XP is our number one quality goal. We need to make sure we get it right. That means several iterations. That means we should implement our own parser to get the flexibility we need to experiment.
Let's have a look at that next week?

**Comment by slu-it** [comment]
@bitterblue 
Ok, after our discussion (earlier F2F) I agree with you. We should implement our own expression DSL and engine. Should we create a ADR for this? If yes, could you?

**Comment by bitterblue** [comment]
I'll handle it.
