### ISSUE TITLE
Should we implement the engine in Kotlin?

### ISSUE THREAD

**Issue by slu-it** [testIT-LivingDoc/livingdoc2#37]
Since the `livingdoc-engine` is an _internal_ module on which no external code should have a dependency, we could implement it in something JVM-based but not good old Java. How about Kotlin?

**Comment by bitterblue** [comment]
Sure, I'm open for the experiment! I actually started implementing a version of the Levenshtein algorithm in Kotlin. It looks extremely like Java, and it should be simple to convert back, should it turn out to be a bad idea :+1:

**Comment by slu-it** [comment]
Good, I also experimented a little bit with it in the context of Microservices. I'm rather confident that Kotlin is a good horse to bet on.

Spring has been supporting it for a while now and with Spring 5 Kotline will be made a first class language for working with Spring. In addition it is also supported as a language for Gradle and can even be compiled to JavaScript (if we need to).

**Comment by slu-it** [comment]
Decision: Yes, we are implementing the `livingdoc-engine` module in Kotlin. API modules will still be defined in Java since this is our primary target language. But we are going to try and make our APIs as Kotlin friendly as possible.
