### ISSUE TITLE
BooleanConverter might need to handle localization

### ISSUE THREAD

**Issue by slu-it** [testIT-LivingDoc/livingdoc2#42]
The `BooleanConverter` currently supports only `true` and `false` as valid values. In documentations `yes` and `no` are more common. In addition these are usually localized (e.g. german: `ja` and `nein`).

How do we want to handle this?

My first idea: provide the translation for the top ~25 languages out of the box and make it possible to override / add additional languages via configuration. (e.g. properties files on classpath for override)

**Comment by bitterblue** [comment]
I think, right now it's important that fixture developers can add their own `TypeConverter`s. I don't think we can anticipate all the needs of a fixture developer, so it's important we provide extension points. To me, that's an important part of the developer experience (quality goal!).

Domain experts and fixture developers will talk in their domain language, which is usually hosted by a natural language. Even if we support different natural languages, the fixture developer still has to add support for the domain. That's the job.
So, I prefer to keep support for specific languages out of the LD2 core components and only provide the mechanics needed for language-specific extensions. As a fixture developer, I would vastly prefer adding a custom type converter for boolean values in my domain language over having to tweak configuration files.

**Comment by pkleimann** [comment]
Decision: No localization for Boolean Converter.
