### ISSUE TITLE
FloatConverter and DoubleConverter might need to handle localization

### ISSUE THREAD

**Issue by slu-it** [testIT-LivingDoc/livingdoc2#43]
The `FloatConverter` and `DoubleConverter` currently supports only whatever `Float.parse(..)` / `Double.parse(..)` can handle. Since documentation is usually written in the target customer's / team's language, the floating point separator might not be a `.`. (e.g. getman: `,`)

How do we want to handle this?

**Comment by bitterblue** [comment]
I had this problem once parsing French floating point numbers. There are locale-aware parsers (I think it was `NumberFormat`). We probably should use those in the default type converters. The current locale is detected by the JVM during startup and can be overridden.

**Comment by slu-it** [comment]
Ok, I'll code something up :)

**Comment by slu-it** [comment]
Implementation: #44
