### ISSUE TITLE
Move User Story Maps to GitHub

### ISSUE THREAD

**Issue by AmraAvdic** [testIT-LivingDoc/livingdoc2#57]
Should we create an adoc or just commit the images?

**Comment by slu-it** [comment]
I think the story maps should be converted to a backlog of stories. The maps themselves are not very interesting (?)

**Comment by pkleimann** [comment]
I decision is to create 3 Projects for each stakeholder (Admin, Business, Developer). Inside these projects we can add columns for the activities. Inside each columns we can add the actions for the activity.
